#spring.application.name=Jakima
spring.application.name=Jakima Estate
server.port=8082
server.servlet.context-path=/
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/jakima_estate
spring.datasource.username=postgres
spring.datasource.password=Langat001
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evanskopir@gmail.com
spring.mail.password=irkraavqlrfphcef
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8

app.jwtSecret=dGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIGp3dCBzZWNyZXQga2V5IHRoYXQgaXMgYXQgbGVhc3QgNTEyIGJpdHMgbG9uZyBmb3IgSFM1MTIgYWxnb3JpdGhtIGluIHByb2R1Y3Rpb24gZW52aXJvbm1lbnQ=
app.jwtExpirationMs=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

cloudinary.cloud-name=dtpczagws
cloudinary.api-key=522661138487521
cloudinary.api-secret=78aM_oOfmEEVV_zrXQ-2Ddqn1q0

whatsapp.api.url=https://wa.me/
whatsapp.business.phone=254719127100

file.upload-dir=uploads/